### ISSUE TITLE
Run aborted at Step 3

### ISSUE THREAD

**Issue by bishav6708** [metageni/FOCUS#20]
I get the following error message:

Counting 7-mers for /input.fasta
jellyfish count -m 7 -o 99189_kmer_counting -s 100M -t 32 -C --disk /input.fasta
Failed to open input file '99189_kmer_counting'
./focus.py:194: RuntimeWarning: invalid value encountered in divide
  return result/(SUM(result)*1.)

Can I know what went wrong here?

**Comment by metageni** [comment]
What is your jellyfish version? My guess is that you are not using the recommended version I put on the tool README. Let me know

**Comment by bishav6708** [comment]
The error was actually on the limit for number of files that can be handled. We fixed that and it worked. Thanks.

Regarding the input file, for paired end reads, do we merge those two files and take that as input file or is there any other method to do so. I have quality controlled forward and reverse reads. Also, I have singleton files. What approach can be better?

**Comment by metageni** [comment]
All the sequences (even singleton) for a sample should go into a unique FASTA/FASTQ. The k-mer composition is computed by file.

**Comment by bishav6708** [comment]
so basically we merge that into a unique FASTA/FASTQ file, correct?

**Comment by metageni** [comment]
Correct. Depending on how much coverage you have on your samples, only one pair will do it. But of course the more coverage, the better- that's why joining all the FASTA/FASTQ per sample is better.

**Comment by bishav6708** [comment]
Thank you for the comments. I really appreciate it.
