### ISSUE TITLE
incorrect link to Jellyfish

### ISSUE THREAD

**Issue by Mark1plus1** [metageni/FOCUS#5]
You have currently included the wrong Jellyfish package in your README.md. Please change it from https://anaconda.org/conda-forge/jellyfish to https://github.com/gmarcais/Jellyfish/releases

**Comment by metageni** [comment]
@Mark1plus1 you are right - I do have the wrong link. I added the bioconda because it is better for MacOS users. I will add the one you send and next to it MacOS link. 

Best

**Comment by Mark1plus1** [comment]
@metageni please note that the package you have linked within the README is still incorrect. Although the currently linked packages is named [Jellyfish v 0.6.1](https://anaconda.org/conda-forge/jellyfish), it is an unrelated "library for doing approximate and phonetic matching of strings."

If you want to link to Bioconda, you can use [this link which is the Jellyfish v 2.2.10](https://anaconda.org/bioconda/jellyfish), a tool for counting of k-mers in DNA.

**Comment by metageni** [comment]
@Mark1plus1 Thanks for noticing it. I have updated it.
