### ISSUE TITLE
Combining Jellyfish Output Files

### ISSUE THREAD

**Issue by linsalrob** [metageni/FOCUS#8]
There is an issue when you have a large fastq file, and jellyfish makes several output files - even with jf >=2.0

For example, download this [algae metagenome data set](https://goo.gl/zvnZD4) which has 50,000 reads and 11,685,706 bp. 

If you extract everything:

```bash
$ ls -l Algae/
total 91104
-rw-r--r-- 1  24392289 Nov 16 16:48 Coral_11.fastq
-rw-r--r-- 1  24733707 Nov 16 16:48 Coral_12.fastq
-rw-r--r-- 1  20770734 Nov 16 16:48 Coral_13.fastq
-rw-r--r-- 1  23352839 Nov 16 16:48 Coral_14.fastq
```

and run focus:

```bash
$ focus -q Algae/ -o Algae_Focus
[2018-11-16 17:26:48,830 - INFO] FOCUS: An Agile Profiler for Metagenomic Data
[2018-11-16 17:26:48,831 - INFO] OUTPUT: Algae_Focus does not exist - just created it :)
[2018-11-16 17:26:48,831 - INFO] 1) Loading Reference DB
[2018-11-16 17:26:50,084 - INFO] 2) Reference DB was loaded with 2785 reference genomes
[2018-11-16 17:26:50,086 - INFO] 3.1) Working on: Coral_11.fastq
[2018-11-16 17:26:50,086 - INFO]    Counting k-mers
Segmentation fault (core dumped)
Failed to open input file 'kmer_counting_0.42009467543622836'
rm: cannot remove 'kmer_counting_0.42009467543622836': No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/focus", line 11, in <module>
    load_entry_point('metagenomics-focus==1.4', 'console_scripts', 'focus')()
  File "/usr/local/lib/python3.6/dist-packages/metagenomics_focus-1.4-py3.6.egg/focus_app/focus.py", line 310, in main
    query_count = normalise(count_kmers(Path(query, temp_query), kmer_size, threads, kmer_order))
  File "/usr/local/lib/python3.6/dist-packages/metagenomics_focus-1.4-py3.6.egg/focus_app/focus.py", line 148, in count_kmers
    raise Exception('{} has no k-mers count. Probably not valid file'.format(query_file))
Exception: Algae/Coral_11.fastq has no k-mers count. Probably not valid file
```

The exception is that it cannot remove `kmer_counting_0.42009467543622836` however, that file doesn't exist, instead I have the following k-mer files:

```
kmer_counting_0.420094675436228360   kmer_counting_0.4200946754362283611  kmer_counting_0.420094675436228362  kmer_counting_0.420094675436228365  kmer_counting_0.420094675436228368 kmer_counting_0.420094675436228361   kmer_counting_0.4200946754362283612  kmer_counting_0.420094675436228363  kmer_counting_0.420094675436228366  kmer_counting_0.420094675436228369 kmer_counting_0.4200946754362283610  kmer_counting_0.4200946754362283613  kmer_counting_0.420094675436228364  kmer_counting_0.420094675436228367
```

If I take a subset of these reads, and run `focus` it works great.

**Comment by metageni** [comment]
Thanks for reporting this @linsalrob. 

I had the same problem using a specific version of Jellyfish. Which version of jellyfish are you using? I think I fixed the problem when I switched it to `2.2.6`.

Moreover, If you don't mind, please run jellyfish on the same big file and probably will get the same `Segmentation fault` error message. Please report it to the jellyfish team (https://github.com/gmarcais/Jellyfish/issues)

I will leave the issue open so I can remember to add some logic to the code, so it fails gracefully if Jellyfish drops the ball.

**Comment by metageni** [comment]
@linsalrob I have created a PR for the future release if FOCUS 1.5. It should have better error handling when Jellyfish fails to calculate the k-mers.

https://github.com/metageni/FOCUS/pull/9

**Comment by metageni** [comment]
Closing this. I have merged the change that will handle this kind of error better.
